[package]
name = "test_annotated_no_value"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "test_annotated_no_value"
path = "test_annotated_no_value.rs"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
